apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-core
  labels:
    app: prometheus
    component: core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
      component: core
  template:
    metadata:
      name: prometheus-main
      labels:
        app: prometheus
        component: core
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v1.2.0
        args:
          - '-storage.local.retention=6h'
          - '-storage.local.memory-chunks=500000'
          - '-config.file=/etc/prometheus/prometheus.yml'
          - '-alertmanager.url=http://alertmanager:9093'
        ports:
        - name: webui
          containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        - name: data-volume
          mountPath: /prometheus
      # nodeSelector:
      #   kubernetes.io/hostname: 192.168.1.110
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-core
      - name: data-volume
        hostPath:
          # directory location on host
          path: /prometheusData
